spring:
  application:
    name: boot-modules

  datasource:
    url: "jdbc:mysql://localhost:3306/spring_boot"
    username: "root"
    password: "@Mythsri.com10"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
# hikari:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"